# Generated by Django 6.0.7 on 2026-07-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_talent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talents/'),
        ),
    ]
