from django.core.management.base import BaseCommand
from jobs.models import Talent


class Command(BaseCommand):
    help = 'Seeds the database with initial talents'

    def handle(self, *args, **kwargs):
        talents_data = [
            {
                'name': "Kifle Alemu", 'role': "Senior Civil Engineer", 'location': "Addis Ababa",
                'price': 65000, 'rating': 4.9, 'reviews': 42,
                'skills': ["AutoCAD", "Project Mgmt", "Structural"],
                'image': "https://i.pravatar.cc/150?u=11", 'category': "Construction",
                'verified': True, 'top': True, 'duration': "Monthly", 'type': "Contract",
                'bio': "Experienced civil engineer with 10+ years in high-rise projects.",
                'tier': 3,
                'sub_ratings': {'quality': 4.9, 'punctuality': 4.8, 'communication': 5.0},
                'portfolio': ["https://images.unsplash.com/photo-1541888940-fcf49be9ae-4374-96d8-98c6-0c768f5c38e3?w=500&q=80"],
                'availability': ["Mon", "Tue", "Wed", "Thu", "Fri"],
                'radius': 20, 'remote': False, 'experience': 12,
                'education': "MSc Civil Engineering",
                'languages': ["English", "Amharic"], 'available_from': 0,
                'certifications': ["PMP", "AutoCAD Pro"]
            },
            {
                'name': "Abebech Teka", 'role': "Financial Consultant", 'location': "Remote",
                'price': 80000, 'rating': 5.0, 'reviews': 18,
                'skills': ["Finance Strategy", "Audit", "Tax"],
                'image': "https://i.pravatar.cc/150?u=21", 'category': "Consultancy",
                'verified': True, 'top': False, 'duration': "Annually", 'type': "Contract",
                'bio': "CPA certified helping startups and SMEs optimize cash flow.",
                'tier': 2,
                'sub_ratings': {'quality': 5.0, 'punctuality': 4.5, 'communication': 4.8},
                'portfolio': [], 'availability': ["Mon", "Wed", "Fri"],
                'radius': 0, 'remote': True, 'experience': 8,
                'education': "MBA", 'languages': ["English"], 'available_from': 2,
                'certifications': ["CPA", "CFA"]
            },
            {
                'name': "Abel Kassa", 'role': "Fullstack Developer", 'location': "Addis Ababa",
                'price': 45000, 'rating': 4.9, 'reviews': 42,
                'skills': ["React", "Django", "Python"],
                'image': "https://i.pravatar.cc/150?u=1", 'category': "Development",
                'verified': True, 'top': True, 'duration': "Monthly", 'type': "Full-time",
                'bio': "Full-stack wizard building scalable web applications.",
                'tier': 3,
                'sub_ratings': {'quality': 4.9, 'punctuality': 4.9, 'communication': 4.9},
                'portfolio': ["https://images.unsplash.com/photo-1461749280689-d3a4ac0475e3?w=500&q=80"],
                'availability': ["Mon", "Tue", "Wed", "Thu", "Fri"],
                'radius': 15, 'remote': False, 'experience': 5,
                'education': "BSc Computer Science",
                'languages': ["English", "Amharic"], 'available_from': 5,
                'certifications': ["AWS Certified"]
            },
            {
                'name': "Hanna Tadesse", 'role': "Product UI/UX Designer", 'location': "Remote",
                'price': 52000, 'rating': 5.0, 'reviews': 28,
                'skills': ["Figma", "Prototyping", "CSS"],
                'image': "https://i.pravatar.cc/150?u=5", 'category': "Design",
                'verified': True, 'top': True, 'duration': "Hourly", 'type': "Part-time",
                'bio': "Award-winning designer focused on user-centric mobile experiences.",
                'tier': 2,
                'sub_ratings': {'quality': 5.0, 'punctuality': 4.8, 'communication': 5.0},
                'portfolio': ["https://images.unsplash.com/photo-1586717791137-e366919f34dc?w=500&q=80"],
                'availability': ["Tue", "Wed", "Thu"],
                'radius': 0, 'remote': True, 'experience': 6,
                'education': "BA Design", 'languages': ["English"], 'available_from': 1,
                'certifications': ["Google UX"]
            },
            {
                'name': "Dawit Bekele", 'role': "Site Supervisor", 'location': "Hawassa",
                'price': 25000, 'rating': 4.7, 'reviews': 15,
                'skills': ["Safety", "Logistics", "Team Lead"],
                'image': "https://i.pravatar.cc/150?u=3", 'category': "Construction",
                'verified': False, 'top': False, 'duration': "Daily", 'type': "Contract",
                'bio': "Ensuring site safety and efficient material management.",
                'tier': 1,
                'sub_ratings': {'quality': 4.5, 'punctuality': 4.8, 'communication': 4.7},
                'portfolio': [], 'availability': ["Mon", "Fri"],
                'radius': 50, 'remote': False, 'experience': 4,
                'education': "Diploma", 'languages': ["Amharic"], 'available_from': 10,
                'certifications': []
            },
            {
                'name': "Sara Tefera", 'role': "Data Scientist", 'location': "Addis Ababa",
                'price': 75000, 'rating': 4.8, 'reviews': 12,
                'skills': ["Python", "TensorFlow", "SQL"],
                'image': "https://i.pravatar.cc/150?u=9", 'category': "Data",
                'verified': True, 'top': False, 'duration': "Weekly", 'type': "Full-time",
                'bio': "Turning data into actionable business insights.",
                'tier': 3,
                'sub_ratings': {'quality': 4.9, 'punctuality': 4.6, 'communication': 4.8},
                'portfolio': [], 'availability': ["Mon", "Tue", "Wed", "Thu", "Fri"],
                'radius': 10, 'remote': False, 'experience': 7,
                'education': "MSc Data Science",
                'languages': ["English", "Amharic"], 'available_from': 3,
                'certifications': ["IBM Data Science"]
            },
            {
                'name': "Bekele Tekle", 'role': "Electrician & Wiring", 'location': "Addis Ababa",
                'price': 15000, 'rating': 4.6, 'reviews': 22,
                'skills': ["Industrial Wiring", "HVAC", "Schematics"],
                'image': "https://i.pravatar.cc/150?u=13", 'category': "Construction",
                'verified': True, 'top': False, 'duration': "Daily", 'type': "Contract",
                'bio': "Expert in industrial electrical systems and safety compliance.",
                'tier': 2,
                'sub_ratings': {'quality': 4.7, 'punctuality': 4.9, 'communication': 4.5},
                'portfolio': ["https://images.unsplash.com/photo-1621905252509-ff2c9d8d7158?w=500&q=80"],
                'availability': ["Mon", "Wed", "Fri"],
                'radius': 25, 'remote': False, 'experience': 10,
                'education': "Vocational Training", 'languages': ["Amharic"], 'available_from': 2,
                'certifications': ["Master Electrician"]
            },
            {
                'name': "Marta Girma", 'role': "Management Consultant", 'location': "Remote",
                'price': 90000, 'rating': 4.9, 'reviews': 30,
                'skills': ["Strategy", "Operations", "HR"],
                'image': "https://i.pravatar.cc/150?u=45", 'category': "Consultancy",
                'verified': True, 'top': True, 'duration': "Special Units", 'type': "Contract",
                'bio': "Strategic partner for organizational growth and efficiency.",
                'tier': 3,
                'sub_ratings': {'quality': 4.9, 'punctuality': 5.0, 'communication': 5.0},
                'portfolio': [], 'availability': ["Mon", "Tue", "Wed", "Thu", "Fri"],
                'radius': 0, 'remote': True, 'experience': 15,
                'education': "PhD Management",
                'languages': ["English", "French"], 'available_from': 0,
                'certifications': ["MBCS"]
            },
            {
                'name': "Elias Mulugeta", 'role': "React Native Dev", 'location': "Addis Ababa",
                'price': 55000, 'rating': 4.7, 'reviews': 10,
                'skills': ["React Native", "iOS", "Android"],
                'image': "https://i.pravatar.cc/150?u=15", 'category': "Development",
                'verified': False, 'top': False, 'duration': "Monthly", 'type': "Full-time",
                'bio': "Building cross-platform mobile apps for the African market.",
                'tier': 1,
                'sub_ratings': {'quality': 4.6, 'punctuality': 4.7, 'communication': 4.8},
                'portfolio': [], 'availability': ["Mon", "Wed", "Fri"],
                'radius': 15, 'remote': False, 'experience': 3,
                'education': "BSc Software Eng",
                'languages': ["English", "Amharic"], 'available_from': 7,
                'certifications': []
            },
            {
                'name': "Zerihun W/Michael", 'role': "Architect", 'location': "Addis Ababa",
                'price': 70000, 'rating': 4.9, 'reviews': 25,
                'skills': ["SketchUp", "3D Modeling", "Interior Design"],
                'image': "https://i.pravatar.cc/150?u=19", 'category': "Construction",
                'verified': True, 'top': True, 'duration': "Project", 'type': "Contract",
                'bio': "Creative architect blending modern design with traditional aesthetics.",
                'tier': 3,
                'sub_ratings': {'quality': 4.9, 'punctuality': 4.9, 'communication': 4.8},
                'portfolio': ["https://images.unsplash.com/photo-15033877310-89c8a832e4d6?w=500&q=80"],
                'availability': ["Mon", "Tue", "Wed", "Thu", "Fri"],
                'radius': 10, 'remote': False, 'experience': 12,
                'education': "MSc Architecture",
                'languages': ["English", "Amharic"], 'available_from': 0,
                'certifications': ["LEED AP"]
            },
            {
                'name': "Selamawit Getachew", 'role': "Graphic Designer", 'location': "Remote",
                'price': 20000, 'rating': 4.5, 'reviews': 18,
                'skills': ["Photoshop", "Illustrator", "Branding"],
                'image': "https://i.pravatar.cc/150?u=22", 'category': "Design",
                'verified': False, 'top': False, 'duration': "Hourly", 'type': "Part-time",
                'bio': "Freelance graphic designer specializing in brand identity.",
                'tier': 1,
                'sub_ratings': {'quality': 4.4, 'punctuality': 4.5, 'communication': 4.6},
                'portfolio': ["https://images.unsplash.com/photo-1627384103962-e3c966b4a826?w=500&q=80"],
                'availability': ["Tue", "Thu"],
                'radius': 0, 'remote': True, 'experience': 2,
                'education': "BA Fine Arts", 'languages': ["English"], 'available_from': 1,
                'certifications': []
            },
            {
                'name': "Yonas Gebreyohannes", 'role': "Business Analyst", 'location': "Remote",
                'price': 60000, 'rating': 4.8, 'reviews': 9,
                'skills': ["SQL", "Excel", "Requirement Gathering"],
                'image': "https://i.pravatar.cc/150?u=25", 'category': "Consultancy",
                'verified': True, 'top': False, 'duration': "Monthly", 'type': "Contract",
                'bio': "Bridging the gap between business needs and technical solutions.",
                'tier': 2,
                'sub_ratings': {'quality': 4.8, 'punctuality': 4.7, 'communication': 4.9},
                'portfolio': [], 'availability': ["Mon", "Tue", "Fri"],
                'radius': 0, 'remote': True, 'experience': 5,
                'education': "MBA", 'languages': ["English", "Amharic"], 'available_from': 4,
                'certifications': ["CBAP"]
            },
            {
                'name': "Bethelhem Tsegaye", 'role': "Digital Marketer", 'location': "Bahir Dar",
                'price': 28000, 'rating': 4.6, 'reviews': 12,
                'skills': ["SEO", "Social Media", "Content Writing"],
                'image': "https://i.pravatar.cc/150?u=30", 'category': "Development",
                'verified': False, 'top': False, 'duration': "Monthly", 'type': "Full-time",
                'bio': "Growth hacker helping brands dominate digital spaces.",
                'tier': 1,
                'sub_ratings': {'quality': 4.6, 'punctuality': 4.6, 'communication': 4.5},
                'portfolio': [], 'availability': ["Mon", "Wed"],
                'radius': 5, 'remote': False, 'experience': 3,
                'education': "BA Marketing", 'languages': ["Amharic"], 'available_from': 6,
                'certifications': []
            },
            {
                'name': "Samuel Asfaw", 'role': "Heavy Machine Operator", 'location': "Hawassa",
                'price': 18000, 'rating': 4.7, 'reviews': 14,
                'skills': ["Excavator", "Bulldozer", "Safety"],
                'image': "https://i.pravatar.cc/150?u=33", 'category': "Construction",
                'verified': False, 'top': False, 'duration': "Daily", 'type': "Contract",
                'bio': "Certified operator for heavy construction machinery.",
                'tier': 1,
                'sub_ratings': {'quality': 4.6, 'punctuality': 4.8, 'communication': 4.7},
                'portfolio': [], 'availability': ["Mon", "Fri"],
                'radius': 50, 'remote': False, 'experience': 6,
                'education': "Certificate", 'languages': ["Amharic"], 'available_from': 8,
                'certifications': []
            },
            {
                'name': "Mekonnen Belay", 'role': "Backend Engineer", 'location': "Addis Ababa",
                'price': 60000, 'rating': 4.8, 'reviews': 21,
                'skills': ["Node.js", "PostgreSQL", "AWS"],
                'image': "https://i.pravatar.cc/150?u=35", 'category': "Development",
                'verified': True, 'top': False, 'duration': "Monthly", 'type': "Full-time",
                'bio': "Building robust backend systems for high-traffic apps.",
                'tier': 2,
                'sub_ratings': {'quality': 4.9, 'punctuality': 4.8, 'communication': 4.8},
                'portfolio': [], 'availability': ["Mon", "Tue", "Wed", "Thu", "Fri"],
                'radius': 10, 'remote': False, 'experience': 6,
                'education': "BSc CS", 'languages': ["English", "Amharic"], 'available_from': 2,
                'certifications': ["AWS Solutions Architect"]
            },
            {
                'name': "Kidist Alemu", 'role': "HR Consultant", 'location': "Remote",
                'price': 75000, 'rating': 5.0, 'reviews': 8,
                'skills': ["Recruitment", "Policy", "Training"],
                'image': "https://i.pravatar.cc/150?u=40", 'category': "Consultancy",
                'verified': True, 'top': True, 'duration': "Project", 'type': "Contract",
                'bio': "Expert in human capital management and organizational culture.",
                'tier': 3,
                'sub_ratings': {'quality': 5.0, 'punctuality': 5.0, 'communication': 5.0},
                'portfolio': [], 'availability': ["Mon", "Tue", "Thu"],
                'radius': 0, 'remote': True, 'experience': 10,
                'education': "MSc HRM", 'languages': ["English", "Amharic"], 'available_from': 0,
                'certifications': ["SHRM-CP"]
            },
            {
                'name': "Tadesse Kebede", 'role': "Plumber", 'location': "Addis Ababa",
                'price': 12000, 'rating': 4.4, 'reviews': 10,
                'skills': ["Installation", "Repair", "Piping"],
                'image': "https://i.pravatar.cc/150?u=50", 'category': "Construction",
                'verified': False, 'top': False, 'duration': "Daily", 'type': "Contract",
                'bio': "Reliable plumbing services for residential and commercial sites.",
                'tier': 1,
                'sub_ratings': {'quality': 4.3, 'punctuality': 4.5, 'communication': 4.4},
                'portfolio': [], 'availability': ["Mon", "Wed"],
                'radius': 10, 'remote': False, 'experience': 8,
                'education': "Vocational", 'languages': ["Amharic"], 'available_from': 3,
                'certifications': []
            },
            {
                'name': "Meron Gebremichael", 'role': "ML Engineer", 'location': "Addis Ababa",
                'price': 95000, 'rating': 4.9, 'reviews': 5,
                'skills': ["Python", "PyTorch", "NLP"],
                'image': "https://i.pravatar.cc/150?u=55", 'category': "Data",
                'verified': True, 'top': True, 'duration': "Weekly", 'type': "Full-time",
                'bio': "Developing intelligent systems to automate complex tasks.",
                'tier': 3,
                'sub_ratings': {'quality': 4.9, 'punctuality': 4.8, 'communication': 4.9},
                'portfolio': ["https://images.unsplash.com/photo-1551288049-bebfda004ce4-9c2da61464e2?w=500&q=80"],
                'availability': ["Mon", "Tue", "Wed", "Thu", "Fri"],
                'radius': 5, 'remote': False, 'experience': 9,
                'education': "PhD AI", 'languages': ["English", "Amharic"], 'available_from': 1,
                'certifications': ["Deep Learning Specialization"]
            },
        ]

        for data in talents_data:
            Talent.objects.update_or_create(name=data['name'], defaults=data)

        self.stdout.write(
            self.style.SUCCESS(f'Successfully seeded {len(talents_data)} talents!')
        )